# Generated by Django 4.2 on 2025-10-04 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom_commun', models.CharField(help_text='Ex: Truite Arc en ciel', max_length=100, verbose_name='Nom commun')),
                ('nom_scientifique', models.CharField(help_text='Ex: Oncorhynchus mykiss', max_length=100, verbose_name='Nom scientifique')),
                ('est_actif', models.BooleanField(default=True, help_text='Cocher si cette espèce est acutellement élevée', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
                'ordering': ['nom_commun'],
            },
        ),
    ]
