# Generated by Django 4.2 on 2025-09-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleveTempOxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateField(auto_now=True, verbose_name='Date de modification')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Température (°C)')),
                ('oxygene', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Oxygène')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pisci.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pisci.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
