# Generated by Django 4.2 on 2025-09-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pisci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevetempoxy',
            name='moment_jour',
            field=models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir')], default='matin', max_length=5, verbose_name='Moment de la journée'),
            preserve_default=False,
        ),
    ]
