# Generated by Django 4.2 on 2025-10-13 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especes', '0001_initial'),
        ('sites', '0001_initial'),
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotDePoisson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_arrivee', models.DateField(help_text="Date d'arrivée du lot sur site", verbose_name="Date d'arrivée")),
                ('quantite', models.PositiveIntegerField(help_text="Nombre d'oeufs reçus initialement", verbose_name='Quantité initiale')),
                ('statut', models.CharField(choices=[('OEUF', 'Œufs'), ('ALEVIN', 'Alevin'), ('TRUITELLE', 'Truitelle'), ('PORTION', 'Portion'), ('GROSSE(G)', 'Grosse'), ('TRES GROSSE(TG)', 'TG')], default='OEUF', max_length=20, verbose_name='Statut')),
                ('code_lot', models.CharField(help_text="Code unique identifiant d'un lot", max_length=20, unique=True, verbose_name='Code lot')),
                ('poids', models.FloatField(help_text='Poids reçu à livraison du lot', verbose_name='poids initial')),
                ('quantite_actuelle', models.PositiveBigIntegerField(default=0, help_text='Quantité actuelle de poisson dans le lot', verbose_name='Quantité actuelle')),
                ('poids_moyen', models.FloatField(blank=True, help_text="Poids moyen d'un poisson (calculé automatiquement)", null=True, verbose_name='Poids moyen (g)')),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_poissons', to='sites.bassin', verbose_name='Bassin')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='especes.espece', verbose_name='Espèce')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_fournis', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
                ('site_prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_poissons', to='sites.site', verbose_name='Site de production')),
            ],
            options={
                'verbose_name': 'Lot de poissons',
                'verbose_name_plural': 'Lots de poissons',
                'ordering': ['-date_arrivee'],
                'permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='lotdepoisson',
            constraint=models.CheckConstraint(check=models.Q(('quantite__gt', 0)), name='quantite_positive'),
        ),
    ]
