# Generated by Django 4.2 on 2025-09-26 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'alliment")),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(max_length=5, verbose_name="Type de l'aliment")),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseurs.fournisseurs', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Aliment',
                'verbose_name_plural': 'Aliments',
                'ordering': ['categorie'],
            },
        ),
    ]
