# Generated by Django 4.2.14 on 2025-10-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
    ]
