# Generated by Django 4.2 on 2025-10-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_fournisseur'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdepoisson',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_fournis', to='fournisseurs.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
