# Generated by Django 4.2 on 2025-10-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotdepoisson',
            options={'ordering': ['-date_arrivee'], 'verbose_name': 'Lot de poissons', 'verbose_name_plural': 'Lots de poissons'},
        ),
    ]
