# Generated by Django 4.2 on 2025-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_lotdepoisson_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdepoisson',
            name='statut',
            field=models.CharField(choices=[('OEUF', 'Œufs'), ('ALEVIN', 'Alevin'), ('TRUITELLE', 'Truitelle'), ('PORTION', 'Portion'), ('GROSSE(G)', 'Grosse'), ('TRES GROSSE(TG)', 'TG')], default='OEUF', max_length=20, verbose_name='Statut'),
        ),
    ]
