# Generated by Django 4.2.14 on 2025-10-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_declare_lotdepoisson_bassins_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdepoisson',
            name='code_lot',
            field=models.CharField(help_text="Code unique identifiant d'un lot", max_length=20, verbose_name='Code lot'),
        ),
    ]
