# Generated by Django 4.2.14 on 2025-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_lotdepoisson_code_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotdepoisson',
            name='dernier_nourrissage',
            field=models.DateTimeField(blank=True, help_text='Date et heure du dernier nourrissage', null=True, verbose_name='Dernier nourrissage'),
        ),
    ]
