# Generated by Django 4.2.14 on 2026-01-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_bassin_site'),
        ('stocks', '0005_lotdepoisson_dernier_nourrissage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdepoisson',
            name='site_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_poissons', to='sites.site', verbose_name='Site de production'),
        ),
    ]
