# Generated by Django 4.2 on 2025-09-30 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': "L'adresse email est obligatoire", 'unique': 'Un utilisateur avec cet email existe déjà'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Adresse mail invalide')], verbose_name='Adresse e-mail'),
        ),
    ]
