# Generated by Django 4.2 on 2025-10-13 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(help_text='Format attendu : 5 Chiffres (ex: 35000)', max_length=6, verbose_name='Code Postal')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de contact')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('est_actif', models.BooleanField(default=True)),
                ('type_fournisseur', models.CharField(choices=[('ALIMENT', 'Aliment'), ('OEUFS', 'Oeufs'), ('MATERIEL', 'Matériel')], help_text='Catégorie principale du fournisseur', max_length=20, verbose_name='Type de fournisseur')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
    ]
