# Generated by Django 4.2 on 2025-10-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_lotdepoisson_fournisseur'),
        ('fournisseurs', '0002_fournisseur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fournisseurs',
        ),
    ]
