# Generated by Django 4.2 on 2025-10-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_delete_fournisseurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='code_postal',
            field=models.CharField(help_text='Format attendu : 5 Chiffres (ex: 35000)', max_length=6, verbose_name='Code Postal'),
        ),
    ]
