# Generated by Django 4.2 on 2025-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bassin',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='bassin',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bassin',
            name='type',
            field=models.CharField(blank=True, help_text='categorie ecloserie, grossissement', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bassin',
            name='volume',
            field=models.FloatField(blank=True, help_text='Volume en m3', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='bassin',
            unique_together={('nom', 'site')},
        ),
    ]
