# Generated by Django 4.2 on 2025-10-12 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_bassin_options_bassin_est_actif_bassin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bassin',
            name='volume',
            field=models.FloatField(blank=True, help_text='Volume en m3', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
