# Generated by Django 4.2 on 2025-09-30 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveTempOxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Température (°C)')),
                ('oxygene', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Oxygène (mg/L)')),
                ('moment_jour', models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir')], max_length=5, verbose_name='Moment de la journée')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_temp_oxy', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
