# Generated by Django 4.2 on 2025-10-13 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('aliments', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveTempOxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Température (°C)')),
                ('oxygene', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Oxygène (mg/L)')),
                ('moment_jour', models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir')], max_length=5, verbose_name='Moment de la journée')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_temp_oxy', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nourrissage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('qte', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité(kg)')),
                ('date_repas', models.DateField(verbose_name='Date du repas')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.aliment', verbose_name="Type d'aliment")),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.bassin', verbose_name='Bassin')),
                ('crea_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nourrissages', to='stocks.lotdepoisson', verbose_name='Lot de poissons')),
            ],
            options={
                'verbose_name': 'Repas Journalier',
                'db_table': 'Repas_journ',
            },
        ),
    ]
