# Generated by Django 4.2.14 on 2025-10-29 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite_quotidien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevetempoxy',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Débit (L/min)'),
        ),
        migrations.AlterField(
            model_name='relevetempoxy',
            name='oxygene',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Oxygène (mg/L)'),
        ),
    ]
