# Generated by Django 4.2.14 on 2025-10-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite_quotidien', '0002_relevetempoxy_debit_alter_relevetempoxy_oxygene'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevetempoxy',
            name='date_releve',
            field=models.DateField(blank=True, null=True, verbose_name='Date du repas'),
        ),
        migrations.AlterField(
            model_name='relevetempoxy',
            name='debit',
            field=models.FloatField(blank=True, help_text='Saisissez le débit en litres par minute.', null=True, verbose_name='Débit (L/min)'),
        ),
        migrations.AlterField(
            model_name='relevetempoxy',
            name='moment_jour',
            field=models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir')], max_length=10, verbose_name='Moment de la journée'),
        ),
        migrations.AlterField(
            model_name='relevetempoxy',
            name='oxygene',
            field=models.FloatField(blank=True, help_text="Saisissez le taux d'oxygène en mg/L.", null=True, verbose_name='Oxygène (mg/L)'),
        ),
        migrations.AlterField(
            model_name='relevetempoxy',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Saisir la température en degré Celsius', null=True, verbose_name='Température (°C)'),
        ),
    ]
