# Generated by Django 4.2.14 on 2025-10-24 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0001_initial'),
        ('activite_quotidien', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nourrissage',
            name='motif_absence',
            field=models.CharField(blank=True, choices=[('eau_sale', 'Eau sale'), ('ajeun', 'À jeun'), ('vide', 'Vide'), ('maladie', 'Maladie'), ('autre', 'Autre (préciser en commentaire)')], max_length=20, null=True, verbose_name="Motif d'absence de repas"),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='aliment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aliments.aliment', verbose_name="Type d'aliment"),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='qte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Quantité(kg)'),
        ),
    ]
