# Generated by Django 4.2.14 on 2026-01-11 15:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_lotdepoisson_dernier_nourrissage'),
        ('sites', '0001_initial'),
        ('aliments', '0001_initial'),
        ('activite_quotidien', '0003_relevetempoxy_date_releve_alter_relevetempoxy_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nourrissage',
            name='aliment_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom de l'aliment"),
        ),
        migrations.AddField(
            model_name='nourrissage',
            name='bassin_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du bassin'),
        ),
        migrations.AddField(
            model_name='nourrissage',
            name='crea_lot_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code du lot de poissons'),
        ),
        migrations.AddField(
            model_name='nourrissage',
            name='cree_par_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom de l'utilisateur"),
        ),
        migrations.AddField(
            model_name='nourrissage',
            name='site_prod_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du site de production'),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='aliment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aliments.aliment', verbose_name="Type d'aliment"),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='bassin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.bassin', verbose_name='Bassin'),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='crea_lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nourrissages', to='stocks.lotdepoisson', verbose_name='Lot de poissons'),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='qte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité(kg)'),
        ),
        migrations.AlterField(
            model_name='nourrissage',
            name='site_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Site de production'),
        ),
    ]
