# Generated by Django 4.2.14 on 2025-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite_quotidien', '0003_nourrissage_motif_absence_alter_nourrissage_aliment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nourrissage',
            name='qte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantité(kg)'),
        ),
    ]
