# Generated by Django 4.2.14 on 2026-01-11 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activite_quotidien', '0004_nourrissage_aliment_nom_nourrissage_bassin_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nourrissage',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
    ]
