# Generated by Django 4.2 on 2025-10-06 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0003_delete_fournisseurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name="Nom de l'aliment")),
                ('code_alim', models.CharField(max_length=6, unique=True, verbose_name="Code nom de l'aliment")),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'aliment", verbose_name='Description')),
                ('fournisseur', models.ForeignKey(help_text="Fournisseur de l'aliment", on_delete=django.db.models.deletion.RESTRICT, related_name='aliments', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Aliment',
                'verbose_name_plural': 'Aliments',
                'ordering': ['code_alim'],
            },
        ),
    ]
