# Generated by Django 4.2.14 on 2026-04-12 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='code_alim',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,6}$')], verbose_name="Code nom de l'aliment"),
        ),
    ]
